# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: az login
  displayName: 'Run a one-line script'

- script: |
    .\azcopy make "https://chelseastorage.blob.core.windows.net/sourcecontainer"
    .\azcopy make "https://chelseastorage2.blob.core.windows.net/targetcontainer"
      For ($i=0; $i -le 100; $i++) {
              $file = "C:\blob$i.txt"
              New-Item $file -ItemType File -Value "The first sentence in our file."
              Add-Content $file "The second sentence in our file."
              
              .\azcopy copy $file "https://chelseastorage.blob.core.windows.net/sourcecontainer/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2021-06-10T15:52:22Z&st=2021-06-10T07:52:22Z&spr=https&sig=jSaKedsMy6jWFHY6rbvbeVVaxcP5MlS8K5lgci3lbMo%3D"
        }
        .\azcopy copy 'https://chelseastorage.blob.core.windows.net/sourcecontainer/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2021-06-10T15:52:22Z&st=2021-06-10T07:52:22Z&spr=https&sig=jSaKedsMy6jWFHY6rbvbeVVaxcP5MlS8K5lgci3lbMo%3D' 'https://chelseastorage2.blob.core.windows.net/targetcontainer' --recursive
  displayName: 'Run a multi-line script'
  

  

   

